export const FETCH_CATEGORIES_PENDING = "FETCH_CATEGORIES_PENDING";
export const FETCH_CATEGORIES_SUCCESS = "FETCH_CATEGORIES_SUCCESS";
export const FETCH_CATEGORIES_FAILED = "FETCH_CATEGORIES_FAILED";

export const FETCH_PRODUCTS_PENDING = "FETCH_PRODUCTS_PENDING";
export const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS";
export const FETCH_PRODUCTS_FAILED = "FETCH_PRODUCTS_FAILED";
export const LOAD_MORE_PRODUCT = "LOAD_MORE_PRODUCT";

export const GET_SUBCATEGORIES_PENDING = "GET_SUBCATEGORIES_PENDING"
export const GET_SUBCATEGORIES_SUCCESS = "GET_SUBCATEGORIES_SUCCESS"
export const GET_SUBCATEGORIES_FAIL = "GET_SUBCATEGORIES_FAIL"

export const SELECTED_CATEGORY = "SELECTED_CATEGORY";

export const FETCH_REVIEWS_PRODUCT_PENDING = "FETCH_REVIEWS_PRODUCT_PENDING";
export const FETCH_REVIEWS_PRODUCT_SUCCESS = "FETCH_REVIEWS_PRODUCT_SUCCESS";
export const FETCH_REVIEWS_PRODUCT_FAILED = "FETCH_REVIEWS_PRODUCT_FAILED";

export const ADD_TO_CART = "ADD_TO_CART";
export const DELETE_FROM_CART = "DELETE_FROM_CART";
export const DELETE_ALL_CART = "DELETE_ALL_CART";

export const GET_CUSTOMER_INFO_PENDING = "GET_CUSTOMER_INFO_PENDING"
export const GET_CUSTOMER_INFO_SUCCESS = "GET_CUSTOMER_INFO_SUCCESS"
export const GET_CUSTOMER_INFO_FAIL = "GET_CUSTOMER_INFO_FAIL"

export const SIGN_UP_PENDING = "SIGN_UP_PENDING";
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";
export const SIGN_UP_FAILED = "SIGN_UP_FAILED";

export const SIGN_IN_PENDING = "SIGN_IN_PENDING";
export const SIGN_IN_SUCCESS = "SIGN_IN_SUCCESS";
export const SIGN_IN_FAILED = "SIGN_IN_FAILED";

export const LOGOUT = "LOGOUT";

export const FORGOT_PASS_PENDING = "FORGOT_PASS_PENDING";
export const FORGOT_PASS_SUCCESS = "FORGOT_PASS_SUCCESS";
export const FORGOT_PASS_FAILED = "FORGOT_PASS_FAILED";

export const SET_SHIPPING_ADDRESS = "SET_SHIPPING_ADDRESS";
export const SET_SHIPPING_METHOD = "SET_SHIPPING_METHOD";

export const GET_SHIPPING_METHODS_PENDING = "GET_SHIPPING_METHODS_PENDING";
export const GET_SHIPPING_METHODS_SUCCESS = "GET_SHIPPING_METHODS_SUCCESS";
export const GET_SHIPPING_METHODS_FAILED = "GET_SHIPPING_METHODS_FAILED";

export const GET_PAYMENT_METHODS_PENDING = "GET_PAYMENT_METHODS_PENDING";
export const GET_PAYMENT_METHODS_SUCCESS = "GET_PAYMENT_METHODS_SUCCESS";
export const GET_PAYMENT_METHODS_FAILED = "GET_PAYMENT_METHODS_FAILED";

export const CREATE_ORDER_PENDING = "CREATE_ORDER_PENDING";
export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS";
export const CREATE_ORDER_FAILED = "CREATE_ORDER_FAILED";

export const SELECT_SUB_CATEGORY = "SELECT_SUB_CATEGORY";

export const ADD_WISHLIST = "ADD_WISHLIST"

